### ISSUE TITLE
testasciidoc --update gives unclear errors when missing dependencies

### ISSUE THREAD

**Issue by apjanke** [asciidoc/asciidoc#75]
It looks like the `testasciidoc.py` program has some undocumented dependencies on GNU source-highlight, GNU LilyPond, and GraphViz. When they are missing, it emits a bunch of error messages and stack traces, but still exits with a successful status.

For example, here's what I get when running against the current code in `master`, I get output that looks like this. ([Full output here.](https://gist.github.com/apjanke/5401f6c1636b6a16be01))

```
$ ./tests/testasciidoc.py --force update &>test-update-out-with-missing-deps.txt
$ echo $?
0
```
Output:
```
/bin/sh: source-highlight: command not found
Traceback (most recent call last):
  File "/usr/local/Cellar/asciidoc/8.6.9/etc/asciidoc/filters/graphviz/graphviz2png.py", line 168, in <module>
    app = Application()
  File "/usr/local/Cellar/asciidoc/8.6.9/etc/asciidoc/filters/graphviz/graphviz2png.py", line 68, in __init__
    format_output = subprocess.Popen(["dot", "-T?"], stderr=subprocess.PIPE, stdout=subprocess.PIPE).communicate()[1]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
```

I think it would be better if it checked for its dependencies, and if they were missing, output a brief error message for each one identifying the missing program. And exited with a non-zero status if any dependencies were missing.

**Comment by aerostitch** [comment]
Hi,

The python 2 implementation of asciidoc (which is what this repo is about) is deprecated.
Please move your issue to the python 3 implementation at https://github.com/asciidoc/asciidoc-py3 if still relevant on that newer implementation and close this issue.

Thanks for your help,
Joseph
